---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/WindowsHosts/WindowsServers/1.1.0
  type: udm.ProvisioningPackage
  deployables:
  - name: WindowsServers
    type: terraform.Module
    boundTemplates:
    - Applications/WindowsHosts/WindowsServers/1.1.0/windowsserver
    preScannedPlaceholders: true
    placeholders:
    - AWS_SECRET_KEY
    - AWS_ACCESS_KEY
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    environmentPath: windows-{{project}}/{{project}}-DEV
    automaticDictionary: "true"
    dictionaryPath: windows-{{project}}-dic
    generateCIsFromResources: "true"
    inputVariables:
      project: rrb-aws
      aws_region: us-east-2
      ami: ami-0d5b55fd8cd8738f5
    file: !file "artifacts/Applications/WindowsHosts/WindowsServers/1.1.0/WindowsServers/aws.ec2_instance.zip"
  templates:
  - name: windowsserver
    type: template.overthere.SmbHost
    instanceName: '{{project}}/TEST/windowsserver'
    childTemplates:
    - name: iis_server
      type: template.iis.Server
    address: '{{%outputVariables.windowsserver_public_dns%}}'
    username: root
    password: !value "Applications_WindowsHosts_WindowsServers_1_1_0_windowsserver_password"
